### ISSUE TITLE
asyncio esception: RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by Chachigo** [matan1905/ComfyUI-Serving-Toolkit#22]
Your node was working fine except for sending an image to discord, I have tried other nodes to do this and now I have this error, I have uninstalled the other nodes and tried to reinstall your node and the problem persists. 

```
Client runninglogging in using static token

Cleaning up after 12 tasks.
Closing the event loop.
Exception in thread Thread-13 (discord_runner):
Accept failed on a socket
socket: <asyncio.TransportSocket fd=7720, family=2, type=1, proto=6, laddr=('127.0.0.1', 8189)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 843, in loop
  File "asyncio\windows_events.py", line 854, in _poll
  File "asyncio\windows_events.py", line 597, in finish_accept
OSError: [WinError 995] L’opération d’entrée/sortie a été abandonnée en raison de l’arrêt d’un thread ou à la demande d’une application
Traceback (most recent call last):
  File "F:\PROJECT\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nextcord\client.py", line 868, in run
    loop.run_forever()
  File "asyncio\windows_events.py", line 321, in run_forever
Traceback (most recent call last):
  File "F:\PROJECT\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\main.py", line 250, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 654, in run_until_complete
  File "asyncio\base_events.py", line 597, in run_forever
  File "F:\PROJECT\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\main.py", line 163, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "F:\PROJECT\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 804, in publish_loop
    msg = await self.messages.get()
          ^^^^^^^^^  File "asyncio\base_events.py", line 589, in _check_running
^^^^^^^^^^^^^^^^
  File "asyncio\queues.py", line 158, in get
RuntimeError: This event loop is already running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\PROJECT\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nextcord\client.py", line 120, in _cleanup_loop
    _cancel_tasks(loop)asyncio.exceptions
.CancelledError  File "F:\PROJECT\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nextcord\client.py", line 102, in _cancel_tasks

    loop.run_until_complete(asyncio.gather(*tasks, return_exceptions=True))
  File "asyncio\base_events.py", line 630, in run_until_complete
  File "asyncio\base_events.py", line 589, in _check_running

F:\PROJECT\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable>pause
```

**Comment by Chachigo** [comment]
i reinstall a clean comfyui and it worked surely a conflict between previously installed nodes
